# see: https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.yaml
default: true
MD013:
  line_length: 200
MD033:
  allowed_elements:
    - br
    - img

# MD053/link-image-reference-definitions - Link and image reference definitions should be needed
MD053:
  # Ignored definitions
  ignored_definitions:
    - "//"
    - "comment"
