repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: |
          (?x)^(
              .obsidian/.*|
              技巧/图谱/.obsidian/.*|
              技巧/图谱/.*.canvas
          )$
      - id: trailing-whitespace

  - repo: https://github.com/thlorenz/doctoc
    rev: v2.2.0
    hooks:
      - id: doctoc
        args:
          - --title=## 目录
          - --github

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.33.0
    hooks:
      - id: markdownlint
      - id: markdownlint-fix
